---
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: coloqio-cluster
  region: eu-central-1

nodeGroups:
  - name: ng-1
    instanceType: t2.small
    desiredCapacity: 1

fargateProfiles:
  - name: fp-coloqio
    selectors:
      # All workloads in the "default" Kubernetes namespace will be
      # scheduled onto Fargate:
      - namespace: default
      # All workloads in the "kube-system" Kubernetes namespace will be
      # scheduled onto Fargate:
      - namespace: kube-system

      # Only the coloqio production workloads will be scheduled onto Fargate:
      - namespace: coloqio-frontend-production
      - namespace: coloqio-backend-production
